version: '3.8'

services:
  devsecops-app:
    build: .
    container_name: devsecops-sample-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
